### ISSUE TITLE
Evaluate \todo and \bug (doxygen) comments

### ISSUE THREAD

**Issue by janvdijk** [LoKI-Suite/LoKI-B-cpp#171]
At present, we have 170 `\todo` and 7 `\bug` (Doxygen) comments in the code. We should go through the list and decide which must be fixed before the initial release. We should also ensure that there is (also) an issue for every `\bug` and `\todo` (some can probably be grouped in a single issue).

The list of files that contain `\bug` or `\todo` statements (some spelled differently, like `TODO:`) follows. Let's mark a file as done when it no longer contains todo's/bugs, *or* issues have been created for all remaining ones.

 * [ ] CMakeLists.txt
 * [ ] CMake/LoKIDoc.cmake
 * [ ] ideas/Container.h
 * [ ] ideas/example_cd_discretizer.cpp
 * [ ] ideas/example_hessenberg_extra.cpp
 * [ ] ideas/HessenbergExtra.cpp
 * [ ] ideas/HessenbergExtra.h
 * [ ] ideas/json2lxcat.cpp
 * [ ] ideas/StateContainer.h
 * [ ] ideas/test_statecontainer.cpp
 * [x] LoKI-B/Constant.h
 * [ ] LoKI-B/EedfCollisions.h
 * [ ] LoKI-B/EedfMixture.h
 * [ ] LoKI-B/EedfUtilities.h
 * [ ] LoKI-B/ElectronKinetics.h
 * [ ] LoKI-B/Gas.h
 * [ ] LoKI-B/GasMixture.h
 * [x] LoKI-B/Grid.h
 * [ ] LoKI-B/GridOps.h
 * [ ] LoKI-B/LegacyToJSON.h
 * [ ] LoKI-B/LinearAlgebra.h
 * [ ] LoKI-B/LookupTable.h
 * [ ] LoKI-B/Matrix2Picture.h
 * [ ] LoKI-B/Operators.h
 * [ ] LoKI-B/Output.h
 * [ ] LoKI-B/Range.h
 * [ ] LoKI-B/Simulation.h
 * [ ] LoKI-B/StateEntry.h
 * [ ] LoKI-B/WorkingConditions.h
 * [ ] source/CrossSection.cpp
 * [ ] source/EedfCollisions.cpp
 * [ ] source/EedfMixture.cpp
 * [ ] source/ElectronKinetics.cpp
 * [ ] source/Enumeration.cpp
 * [ ] source/Gas.cpp
 * [ ] source/GasMixture.cpp
 * [x] source/Grid.cpp
 * [ ] source/LegacyToJSON.cpp
 * [ ] source/LinearAlgebra.cpp
 * [x] source/OffSideToJSON.cpp
 * [ ] source/Operators.cpp
 * [ ] source/Output.cpp
 * [ ] source/Parse.cpp
 * [ ] source/Range.cpp
 * [ ] source/StateEntry.cpp
 * [ ] source/WorkingConditions.cpp
 * [ ] tests/test_druyvesteyn.cpp
 * [ ] tests/test_ee.cpp
 * [ ] tests/test_ee_relaxation.cpp
 * [ ] tests/test_integrals.cpp
 * [ ] tests/test_nonuniform_field.cpp
 * [ ] tests/test_nonuniform_inelastic.cpp
 * [ ] tests/test_statebase.cpp
 * [ ] web/bindings.cpp
