### ISSUE TITLE
Master project Jop Hendrikx ToDo list

### ISSUE THREAD

**Issue by JopHendrikx** [LoKI-Suite/LoKI-B-cpp#198]
- [x] Sizing field
- [x] Check Temporal growth routine for nonuniform grids
- [x] Check Equal sharing operator distribution for giving correct indices
- [x] Check reverse reactions
- [x] Solve negative first anisotropy for first couple of cells
- [x] Test OneTakesAll for truly nonuniform grids
- [x] Test exotic molecular input files, O2/CO2/He/DryAir

Written work to be done
- [ ] Introduction/Abstract
- [ ] Method/Adaptive mesh refinement
- [ ] Results Analytical tests (delta peaks)
- [ ] Results Argon/Molecular gasses
- [ ] Conclusion/Outlook
